#!/usr/bin/env python3
import subprocess
import sys

def main():
    if len(sys.argv) < 4:
        print("Usage: gensyms.py <kernel.elf> <output.c> <cross_compile_prefix>")
        sys.exit(1)

    elf_file = sys.argv[1]
    out_c_file = sys.argv[2]
    cross = sys.argv[3]

    nm_bin = f"{cross}nm"
    addr2line_bin = f"{cross}addr2line"

    nm_proc = subprocess.Popen([nm_bin, "-n", "--defined-only", elf_file], stdout=subprocess.PIPE, text=True)
    symbols = []

    for line in nm_proc.stdout:
        parts = line.strip().split()
        if len(parts) >= 3 and parts[1] in ('T', 't'):
            addr = int(parts[0], 16)
            name = parts[2]
            if not name.startswith(('__', '.')):
                symbols.append((addr, name))
    nm_proc.wait()

    addrs_str = "\n".join([f"0x{addr:x}" for addr, _ in symbols])
    a2l_proc = subprocess.Popen([addr2line_bin, "-e", elf_file], stdin=subprocess.PIPE, stdout=subprocess.PIPE, text=True)
    a2l_out, _ = a2l_proc.communicate(input=addrs_str)
    
    file_lines = [line.strip() for line in a2l_out.strip().split("\n")]

    with open(out_c_file, "w") as f:
        f.write("/* Automatically generated by gensyms.py - DO NOT EDIT */\n")
        f.write("#include <stdint.h>\n\n")
        f.write("typedef struct {\n")
        f.write("    uint64_t addr;\n")
        f.write("    const char* name;\n")
        f.write("    const char* file;\n")
        f.write("    uint32_t line;\n")
        f.write("} ksymbol_t;\n\n")

        f.write("const ksymbol_t kernel_symbols[] = {\n")
        for i, (addr, name) in enumerate(symbols):
            fl = file_lines[i] if i < len(file_lines) else "?:0"
            if ":" in fl:
                src_file, line_num = fl.rsplit(":", 1)
                src_file = src_file.replace("\\", "/").split("/")[-1]
                try:
                    line_no = int(line_num)
                except ValueError:
                    line_no = 0
            else:
                src_file = "?"
                line_no = 0

            f.write(f'    {{ 0x{addr:X}ULL, "{name}", "{src_file}", {line_no} }},\n')

        f.write("};\n\n")
        f.write(f"const uint32_t kernel_symbols_count = {len(symbols)};\n")

if __name__ == "__main__":
    main()